language: ko-KR

early_access: true
enable_free_tier: true

reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai 요약"
  auto_title_placeholder: "@coderabbitai"
  poem: true
  review_status: true
  collapse_walkthrough: false
  sequence_diagrams: true
  abort_on_close: true

  path_filters:
    - "!**/README.md"
    - "!**/build/**"
    - "!**/generated/**"
    - "!**/.gradle/**"
    - "!**/src/main/resources/static/docs/**"

  path_instructions:
    # SQL Rules
    - path: "**/*.sql"
      instructions: >
        As a personal convention, i don't specify FK constraints. Please avoid suggesting adding FK constraints in code reviews.
        This file is an SQL file, and the SQL statements that modify the table structure are written as strings. 
        For columns used as primary keys (PK) or foreign keys (FK), you must follow the convention of specifying the column type as "bigint".
        If a table column name is "id" or ends with "_id", verify that the column type is "bigint". If the SQL is written with a type other than "bigint", 
        issue a warning. This convention is mandatory, so please raise the severity level of the warning. 
        Add the following characters to the beginning of the warning message so that users can easily notice it: ⚠️⚠️⚠️

    # Kotlin Common
    - path: "**/*.kt"
      instructions: |
        - Verify compliance with Kotlin coding conventions
        - Check for safe nullable handling (?.let, ?:, avoid excessive use of !!)
        - Review proper usage of data classes
        - Consider opportunities for extension functions

    # Controller (Kotlin)
    - path: "**/*Controller*.kt"
      instructions: >
        Review the API endpoints based on this guidelines.

        ### Richardson Maturity Model (RMM)
        1. Level 0: Single URI with POST requests for all actions.
        2. Level 1: Separate URIs for individual resources.
        3. Level 2: Use of HTTP methods (GET, POST, PUT, DELETE) to define operations on resources.

        ### API Conventions
        - URI Rules:
          - Should be intuitive and self-explanatory.
          - Should not map 1:1 to database tables.
          - Must be stateless, with no session state between requests.
          - Include "api" in the URI (/api/resource).
          - Use kebab-case for URIs and camelCase for parameters and body contents.
          - Resource identifiers should be unique and only one per URI path.

        - Design Principles:
          - APIs should be designed around resources, which are abstractions rather than direct database tables.
          - Stateless APIs facilitate scalability and flexibility.
          - Clear separation of frontend and backend via URI structure.
          - Maintain consistent naming conventions across the API.
          - Use plural nouns for collection resources. (/users instead of /user-list).
          - Complex actions can include verbs in the URI (/orders/{orderId}/cancel).

        - Implementation Details:
          - Avoid deeply nested resource paths to ensure maintainability.
          - Ensure URIs reflect the data they provide, not the permissions or roles required to access them.
          - Keep URIs simple and predictable, aiding both developers and automated systems.

    # DTO / Request / Response
    - path: "**/*Request*.kt"
      instructions: |
        - Verify validation annotations (@NotBlank, @Size, etc.)
        - Check for proper nullable handling
        - Review field naming consistency

    - path: "**/*Response*.kt"
      instructions: |
        - Verify response structure is consistent
        - Check for sensitive data exposure

    # Service Layer
    - path: "**/service/**/*.kt"
      instructions: |
        - Verify @Transactional boundaries are properly defined
        - Check separation of business logic and data access logic
        - Ensure consistent exception handling patterns

    # Repository (QueryDSL)
    - path: "**/repository/**/*.kt"
      instructions: |
        - Review for potential N+1 query problems
        - Check for proper use of fetch joins
        - Verify pagination implementation is correct

    # Entity
    - path: "**/entity/**/*.kt"
      instructions: |
        - Verify lazy loading (LAZY) is set as default for associations
        - Check for convenience methods in bidirectional relationships

    # Security
    - path: "**/security/**/*.kt"
      instructions: |
        - Review authentication/authorization logic carefully
        - Check for potential security vulnerabilities
        - Verify JWT handling is secure
        - ⚠️ Flag any hardcoded secrets or credentials

    # Spring Batch
    - path: "**/batch/**/*.kt"
      instructions: |
        - Review chunk size appropriateness
        - Check Skip/Retry policy configuration
        - Verify separation of ItemReader/Processor/Writer responsibilities

    - path: "**/job/**/*.kt"
      instructions: |
        - Review Job parameter design
        - Verify idempotency is guaranteed

    # Configuration Files
    - path: "**/application*.yml"
      instructions: |
        - Verify environment-specific configurations are properly separated
        - ⚠️ Check for hardcoded secrets or sensitive values

    # Test Code
    - path: "**/test/**/*.kt"
      instructions: |
        - Verify Given-When-Then pattern compliance
        - Check test naming clarity
        - Review appropriate use of mocks

    # Gradle Build
    - path: "**/build.gradle.kts"
      instructions: |
        - Check for potential dependency version conflicts
        - Review module dependency directions

  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: [ ]
    labels: [ ]
    drafts: false
    base_branches: [ ]

  tools:
    detekt:
      enabled: true
    shellcheck:
      enabled: true
    markdownlint:
      enabled: true
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    hadolint:
      enabled: true
    actionlint:
      enabled: true
    biome:
      enabled: true

    github-checks:
      enabled: true
      timeout_ms: 90000

    languagetool:
      enabled: true
      disabled_rules:
        - EN_UNPAIRED_BRACKETS
        - EN_UNPAIRED_QUOTES
      disabled_categories:
        - TYPOS
        - TYPOGRAPHY
        - CASING
      enabled_only: false
      level: default
      enabled_rules: [ ]
      enabled_categories: [ ]

    ast-grep:
      packages: [ ]
      rule_dirs: [ ]
      util_dirs: [ ]
      essential_rules: true

    swiftlint:
      enabled: false
    phpstan:
      enabled: false
    golangci-lint:
      enabled: false
    ruff:
      enabled: false

chat:
  auto_reply: true

knowledge_base:
  learnings:
    scope: auto
  issues:
    scope: auto
  jira:
    project_keys: [ ]
  linear:
    team_keys: [ ]